### ISSUE TITLE
Firebase exception

### ISSUE THREAD

**Issue by brignano** [The-Hartford-Senior-Project-2020/Quote-Chatbot#2]
Hi @clarkent711 @Kare3m1 @brendanpyzik ,

I was told you guys are having an exception with Firebase- can you please share the exception details here so we can take a closer look at it before tomorrow?

Thank you!

**Comment by Kare3m1** [comment]
Hi Anthony, If you go on github there's a repo called firebase-dialogflow
inside it there's a file called HFchatbotFirebase. This is where I did my
work on angular and fire-base (sorry didn't know how to start an empty repo
on pycharm I will look into that later).

if you navigate to
Quote-Chatbot\HFchatbotFirebase\hfchatbot-dialogflowv6\chatbot and do ng
serve you should get a chat bot interface. If it doesn't work try those
commands
"ng update @angular/cli @angular/core"
"npm install --save-dev @angular-devkit/build-angular"

For fire-base I attached a JSON file that you should put in
your \Quote-Chatbot\HFchatbotFirebase\hfchatbot-dialogflowv6\functions
directory, and I run fire-base using "firebase deploy".

If you try to type a message in the chatbot interface and send it will just
keep loading, and on the fire-base console when you refresh it gives me the
error "Error: The incoming JSON object does not contain a client_email
field". I will send you and Kevin an invite to fire-base shortly so you can
see the full error.

Thanks for your help if you need anymore details feel free to email me
Karem Sakr

**Comment by brignano** [comment]
@Kare3m1 - Unfortunately, GitHub strips the email attachments so I am not able to see the JSON you attached. Is there any way you can upload it to an online filestore and share that link here?

Also, I couldn't find the relative path you referenced (\Quote-Chatbot\HFchatbotFirebase\hfchatbot-dialogflowv6\functions) in the master branch so, after doing some digging around the repository, I am assuming you're working in the [firebase-dialogflow branch](https://github.com/The-Hartford-Senior-Project-2020/Quote-Chatbot/tree/firebase-dialogflow/HFchatbotFirebase/hfchatbot-dialogflowv6/functions)?

With that being said, if you can provide me with the JSON file, I can checkout your branch and run the steps you outlined to get the error.

**Comment by Kare3m1** [comment]
yes I meant firebase-dialogflow branch sorry about that. I uploaded the
file to google drive here's the link.

https://drive.google.com/file/d/1_Br021wTotLHyZ_lPVmfB9huPRh5r8FS/view?usp=sharing

**Comment by brignano** [comment]
When trying to run ```ng serve```,

![image](https://user-images.githubusercontent.com/9291621/74896634-c5e15200-5362-11ea-9d4a-5208823aab34.png)

When trying to run ```firebase deploy```,

![image](https://user-images.githubusercontent.com/9291621/74896715-f9bc7780-5362-11ea-8b6d-a0301d1b99ad.png)

I would login to firebase and try deploying again but I haven't gotten any invite email yet so not sure which credentials to use for that. It's probably best if you invite my gmail (anthonybrignano@gmail.com) since I already have a Firebase account setup for that.

Just curious, are you referencing any guide or tutorial for this setup? That might help give me a better context around what you're doing and where you are in the process.

**Comment by Kare3m1** [comment]
I sent you an invite on firebase for that gmail.
For the ng serve I think you need to navigate to the directory where the
angular app is on which is
Quote-Chatbot\HFchatbotFirebase\hfchatbot-dialogflowv6\chatbot

I am referencing this guide
https://fireship.io/lessons/build-a-chatbot-with-dialogflow/

**Comment by brignano** [comment]
Great thanks for the context. Now I'm able to recreate the error but need more analysis to determine the root cause. One thing I noticed is in that guide they reference ```serviceAccount``` instead of the path.

https://github.com/The-Hartford-Senior-Project-2020/Quote-Chatbot/blob/3fb0ca8965f6cd8155bfaa3c9e7dfa188461e115/HFchatbotFirebase/hfchatbot-dialogflowv6/functions/index.js#L5-L10

![image](https://user-images.githubusercontent.com/9291621/74902167-35f7d400-5373-11ea-99fb-ff1c781eebcd.png)

After referencing ```serviceAccount```, I started seeing a different error in the logs,

![image](https://user-images.githubusercontent.com/9291621/74902466-2dec6400-5374-11ea-8dc6-544ec0d38bf3.png)

Not sure if there's any significance to this - I will try to look more into it tomorrow - but I am going on vacation starting Friday, February 21st and returning Monday, March 2nd so I will work to hand the analysis off to @KevinMoore2020 tomorrow also.

**Comment by KevinMoore2020** [comment]
Hi @clarkent711 @Kare3m1 @brendanpyzik ,

I took another look at the firebase issue again along with another Hartford developer who has used firebase before. You have two main cloud functions: a gateway and the webhook. One thing that was unfamiliar with us was the use of the gateway, it seems to be more about authentication. In our experience, authentication is a big challenge when using cloud functions and dialogflow, and both of us remember just skipping it for our projects.  

We were able to make the chatbot work in Dialogflow by changing your fulfillment url form the gateway function to the webhook. Notice how an input of "Hi" always results in the response you put in index.js "Welcome to my agent!".

My recommendation is that you leave out the gateway for now and try to make your code work with just the webhook since the webhook is in fact working! We can discuss the future of the authentication function in later reviews.  

(I did not modify your code, i just tested the webhook in the Dialogflow test ui)

**Comment by Kare3m1** [comment]
That's great Kevin it works on my end as well. We will look into how we can
connect this to angular or just a simple HTML page for now. Thanks for your
help.

**Comment by KevinMoore2020** [comment]
You should be able to keep your existing angular framework, currently your chatbot component makes a call to the gateway but you should be able to replace that with a call to the webhook which will then run your node js functions. Might need to find the right json to send for that call

**Comment by Kare3m1** [comment]
@KevinMoore2020 @brendanpyzik @clarkent711  I have been looking into how to make our current angular framework work with the webhook link but I am getting this error on firebase "Error: Invalid or unknown request type (not a Dialogflow v1 or v2 webhook request).". I tried changing small stuff in what I am sending to the webhook, but no luck. If you guys can take a look at it because I am a little lost. 
Thank you

**Comment by KevinMoore2020** [comment]
@Kare3m1 @brendanpyzik @clarkent711 
I'll have a chance to check this out myself Wednesday evening.

In the meantime, you can find the expected json for the request on dialogflow using the test agent's diagnostic info:
{
  "responseId": "bd3aabb6-a429-4c40-9829-49d7a8daa8ca-7f245a81",
  "queryResult": {
    "queryText": "hello",
    "action": "input.welcome",
    "parameters": {},
    "allRequiredParamsPresent": true,
    "fulfillmentText": "Hi! How are you doing?",
    "fulfillmentMessages": [
      {
        "text": {
          "text": [
            "Hi! How are you doing?"
          ]
        }
      }
    ],
    "outputContexts": [
      {
        "name": "projects/hartford-chatbot-fdsxiy/agent/sessions/a7ae8f29-415f-32e9-1290-995e8c72b0df/contexts/__system_counters__",
        "lifespanCount": 1,
        "parameters": {
          "no-input": 0,
          "no-match": 0
        }
      }
    ],
    "intent": {
      "name": "projects/hartford-chatbot-fdsxiy/agent/intents/307f8d9a-70bd-4442-a4ff-bf5b97890ae5",
      "displayName": "Default Welcome Intent"
    },
    "intentDetectionConfidence": 1,
    "languageCode": "en"
  },
  "originalDetectIntentRequest": {
    "payload": {}
  },
  "session": "projects/hartford-chatbot-fdsxiy/agent/sessions/a7ae8f29-415f-32e9-1290-995e8c72b0df"
}

I'm not sure if this helps, but try and see if you can make the call with this information. If i get a chance to review further I'll let you know

**Comment by Kare3m1** [comment]
@KevinMoore2020 @clarkent711 @brendanpyzik While looking at the json issue I actually found a solution to our first issue with the dialogflow gateway cloud functions. When I hard coded client email and private key into our index.js file I stopped getting the client email error, and I am getting correct responses on the angular framework. The only issue it's a little slow but that's something we can worry about later. I am reluctant about uploading what I have on github because our private api key is in the source code now. I think we should make this repo private so we don't have to worry about this issue.

**Comment by KevinMoore2020** [comment]
@Kare3m1 @clarkent711 @brendanpyzik 
Excellent work! However, even using a private repo isn't 100% secure, especially since your key will also be hosted on the Firebase platform. I would recommend holding off on a commit for now- or at least remove the private key before committing. Lets try and think of another possible solution, and I can also ask other developers for opinions.

That said, can you clarify if you are actually hitting the webhook now? I can refocus my efforts to finding the right way to authenticate the gateway if so.

**Comment by Kare3m1** [comment]
@KevinMoore2020 
I am not sending the request to the webhook link. I am sending it to the gateway link, and it works fine. I also didn't change the link in the fulfillment tab, and it wouldn't matter because when we deploy to firebase it deploys to both links. I think each link has it's own uses, but I am not really sure how all of that works.

**Comment by KevinMoore2020** [comment]
Apologies for my confusion, but are you saying that you are now getting the correct requests and responses using your UI?

**Comment by Kare3m1** [comment]
@KevinMoore2020 
Yes it's working with the ui. I will talk with @clarkent711 to set the repo to private after that's done I will push my stuff. I think we can close this issue for now. Thanks for your help.

**Comment by brignano** [comment]
Closing issue as it has been resolved per @Kare3m1 and @KevinMoore2020. Nice work!
